Subscriber details flow fixes
ukama/ukama pull request #786
Opened 2024-10-13 12:46 UTC by Brackleycassinga

2024-10-14 09:00 UTC, salman-codewar requested changes

2024-10-15 08:37 UTC, Brackleycassinga commented on interfaces/console/src/app/console/subscribers/page.tsx
> +        }
Addressed

2024-10-15 08:38 UTC, Brackleycassinga commented on interfaces/console/src/app/console/subscribers/page.tsx
> +          await Promise.all(deletionPromises);
Michelle mention that we should remove it for now.

2024-10-15 10:08 UTC, Brackleycassinga commented on interfaces/console/src/app/console/subscribers/page.tsx
> +          });
addressed

2024-10-22 14:09 UTC, salman-codewar approved these changes

2024-10-23 13:19 UTC, merged