Add Node/Controller API Module to BFF
ukama/ukama pull request #811
Opened 2024-11-12 13:51 UTC by Brackleycassinga

2024-11-14 09:17 UTC, salman-codewar approved these changes

2024-11-19 06:45 UTC, salman-codewar requested changes
BFF is crashing because if these change. Please try to run and fix it.

2024-11-19 09:43 UTC, delvatt reviewed
As this is a Typescript project and i know nothing about that, I can only give approval  afte @salman-codewar  approval.

2024-11-22 14:51 UTC, salman-codewar requested changes

2024-11-22 15:26 UTC, salman-codewar approved these changes

2024-11-22 16:03 UTC, delvatt approved these changes

2024-11-22 16:13 UTC, merged