Refactor Builder Script: Remove Email Config from Deploy JSON for Mailer Service Env Setup
ukama/ukama pull request #816
Opened 2024-11-16 16:41 UTC by Brackleycassinga

- Removed email configuration from the deploy JSON file.
- Updated the script to allow the email configuration to be passed as environment variables directly in the mailer service.

2024-11-18 13:38 UTC, salman-codewar requested changes

2024-11-18 13:38 UTC, salman-codewar commented on systems/notification/mailer/pkg/config.go
> +		usernameSuffix = "_USERNAME"
I don't think we need to load these configs, It should be available by default.

2024-11-18 17:15 UTC, salman-codewar requested changes

2024-11-18 17:15 UTC, salman-codewar commented on systems/notification/docker-compose.yml
> +   - MAILERUSERNAME=${MAILERUSERNAME}
If you have configs with sub structures you need to add `_` in between. `i.e: MAILERHOST should be MAILER_HOST`

2024-11-18 17:15 UTC, salman-codewar commented on systems/notification/mailer/pkg/config.go
> +	MailerFrom       string `default:"hello@dev.ukama.com"`
Previous implementation was fine.
```
type MailerConfig struct {
	Host     string `default:"localhost"`
	Port     int    `default:"587"`
	Username string `default:""`
	Password string `default:""`
	From     string `default:"hello@dev.ukama.com"`
}
```
& 
`Mailer           *MailerConfig`

What's the reason of change?

2024-11-19 10:01 UTC, salman-codewar approved these changes

2024-11-22 16:07 UTC, delvatt approved these changes

2024-11-22 17:42 UTC, merged